version: '2.1'
services:

    mongodb:
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=nemanja
            - MONGO_INITDB_ROOT_PASSWORD=changeme
        build:
            context: ./mongodb/
        restart: always
        volumes:
            - db-data:/data/db
        ports:
            - 27017:27017
        healthcheck:
            test: exit 0
        networks:
            - mobnet

    test_app:
        container_name: test_app
        build:
            context: ./test_app/
        restart: always
        ports:
            - 80:80
        depends_on:
            mongodb:
                condition: service_healthy
        links:
            - mongodb
        networks:
            - mobnet

    parser:
        container_name: parser
        build:
            context: ./parser/
        restart: always
        ports:
            - 5001:5001
        depends_on:
            mongodb:
                condition: service_healthy
        links:
            - mongodb
        networks:
            - mobnet

volumes:
    db-data:

networks:
    mobnet:
